### ISSUE TITLE
It seems pytorch0.2.0 are not supported under cuda9.0

### ISSUE THREAD

**Issue by pz0910** [baowenbo/MEMC-Net#1]
Are you sure about the environment requirement: pytorch0.2.0_4+cuda9.0+cudnn7.0?
I failed to install pytorch0.2.0 with cuda9.0.
Can you help me out?
And I found a misspelling in README:  './install.sh' should be replaced with './install.bash'

**Comment by baowenbo** [comment]
So sorry, i made a mistake in the README. Pytorch0.2 should be cuda8.0 with cudnn5.0. I also  provide an [environment.yml ](https://github.com/baowenbo/MEMC-Net/blob/master/environment.yml)file for reference.
Thank you~

**Comment by baowenbo** [comment]
Sure we have to use './install.bash'.
